### ISSUE TITLE
Error: 'model' should be truthy

### ISSUE THREAD

**Issue by MobileAppVault** [redux-autoform/redux-autoform#293]
Hi,

I've implemented redux-autoform in my app like this:

```
import React from 'react'
import { Field, reduxForm } from 'redux-form'
import { AutoForm } from 'redux-autoform';
import { EditComponentFactory, DetailsComponentFactory } from 'redux-autoform-bootstrap-ui';

let schema = {
    name: {
        type: 'string',
        displayName: 'Name',
        required: true
    },
	lastName: {
		type: 'string',
		displayName: 'Last Name',
		required: true
	}
};

let autoFormProps = {
    form: 'demo',
    schema:  schema,
    componentFactory: EditComponentFactory,
    onSubmit: (...args) => console.log(args),
    overwriteOnInitialValuesChange: undefined
};

let ContactForm = props => {
  const { handleSubmit } = props
  return (
    <AutoForm {...autoFormProps} />
  )
}

ContactForm = reduxForm({
  // a unique name for the form
  form: 'contact'
})(ContactForm)

export default ContactForm;
```

`Error: 'model' should be truthy
    at Error (native)
    at Function.process (...node_modules\redux-autoform\lib\metadata\model\ModelParser.js:59:31)
    at AutoFormInternal._this.buildGroupComponent (...node_modules\redux-autoform\lib\AutoFormInternal.js:68:47)
    at AutoFormInternal.render (...node_modules\redux-autoform\lib\AutoFormInternal.js:133:30)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (...node_modules\react\lib\ReactCompositeComponent.js:815:34)
    at ReactCompositeComponentWrapper._renderValidatedComponent (...node_modules\react\lib\ReactCompositeComponent.js:841:32)
    at ReactCompositeComponentWrapper.performInitialMount (...node_modules\react\lib\ReactCompositeComponent.js:351:30)
    at ReactCompositeComponentWrapper.mountComponent (...node_modules\react\lib\ReactCompositeComponent.js:244:21)
    at Object.mountComponent (...node_modules\react\lib\ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (...node_modules\react\lib\ReactCompositeComponent.js:357:34)
    at ReactCompositeComponentWrapper.mountComponent (...node_modules\react\lib\ReactCompositeComponent.js:244:21)
    at Object.mountComponent (...node_modules\react\lib\ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (...node_modules\react\lib\ReactCompositeComponent.js:357:34)
    at ReactCompositeComponentWrapper.mountComponent (...node_modules\react\lib\ReactCompositeComponent.js:244:21)
    at Object.mountComponent (...node_modules\react\lib\ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (...node_modules\react\lib\ReactCompositeComponent.js:357:34)
    at ReactCompositeComponentWrapper.mountComponent (...node_modules\react\lib\ReactCompositeComponent.js:244:21)
    at Object.mountComponent (...node_modules\react\lib\ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (...node_modules\react\lib\ReactCompositeComponent.js:357:34)
    at ReactCompositeComponentWrapper.mountComponent (...node_modules\react\lib\ReactCompositeComponent.js:244:21)
    at Object.mountComponent (...node_modules\react\lib\ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (...node_modules\react\lib\ReactCompositeComponent.js:357:34)`

**Comment by JonatanSalas** [comment]
@MobileAppVault why are you using redux-form package? Redux-autoform wraps redux-form to generate the form dynamically. 

Then your code should look like this: 

```jsx
import React from 'react'
import { Field, reduxForm } from 'redux-form'
import { AutoForm } from 'redux-autoform';
import { EditComponentFactory, DetailsComponentFactory } from 'redux-autoform-bootstrap-ui';

const schema = {
    name: {
        type: 'string',
        displayName: 'Name',
        required: true
    },
    lastName: {
	type: 'string',
	displayName: 'Last Name',
	required: true
    }
};

const autoFormProps = {
    form: 'contact',
    schema:  schema,
    componentFactory: EditComponentFactory,
    onSubmit: (...args) => console.log(args),
    overwriteOnInitialValuesChange: undefined
};

const ContactForm = _ => <AutoForm {...autoFormProps} />;

export default ContactForm;
```

Redux-autoForm currently doesn't support redux-form v6/7. There is some work on it, but I have to stopped due to a lack of time.

**Comment by MobileAppVault** [comment]
So when  i try to run redux-autoform without installing "redux-form" than I get the following error 

```
Error: Cannot find module 'redux-form' from '...node_modules\redux-autoform\lib'
    at ...node_modules\browser
-resolve\node_modules\resolve\lib\async.js:46:17
    at process (...node_module
s\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (...node_modules\
browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (...node_modules\b
rowser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (...node_modules\b
rowser-resolve\node_modules\resolve\lib\async.js:92:31)
    at ...node_modules\browser
-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by JonatanSalas** [comment]
You need to install redux-form v5! It's a redux-autoform peer dependency. You can install it by executing: 

```bash
yarn add redux-form@5.3.6
```

or

```
npm install --save redux-form@5.3.6
```

Hope it helps!

**Comment by MobileAppVault** [comment]
Ok, I've try this but now I get:  :(

`Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`

**Comment by JonatanSalas** [comment]
Bad mine, I forget you to specify buttonBar prop in AutoFormProps. I have made an example based from CRA. The code that works is the following one: 

```jsx
import React from 'react'
import { AutoForm } from 'redux-autoform';
import { EditComponentFactory } from 'redux-autoform-bootstrap-ui';

const schema = {
    name: {
        type: 'string',
        displayName: 'Name',
        required: true
    },
    lastName: {
        type: 'string',
        displayName: 'Last Name',
        required: true
    }
};

const autoFormProps = {
    form: 'contact',
    schema:  schema,
    componentFactory: EditComponentFactory,
    onSubmit: (values) => alert(JSON.stringify(values, null, 2)),
    overwriteOnInitialValuesChange: undefined,
    buttonBar: () => <button type="submit">Submit Values</button>
};

const ContactForm = _ => <AutoForm {...autoFormProps} />;

export default ContactForm;
```

Let me know if it works for you!

**Comment by JonatanSalas** [comment]
@MobileAppVault here you have the repo I have made -> https://github.com/JonatanSalas/redux-autoform-test

**Comment by MobileAppVault** [comment]
Ok many thanks this works! I had a typo in my code :(

**Comment by JonatanSalas** [comment]
@MobileAppVault you're welcome! Let me know if you need something else!
